[workspace]
members = ["four", "four_cli", "four_derive", "examples/simple_lambda"]
resolver = "2"

[patch.crates-io]
four = { path = "four" }

[workspace.dependencies]
convert_case = "0.6"
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = "2.0.108"
